// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package autodemosql

type Project struct {
	ID        string
	CreatedAt int64
}

type ProjectDatum struct {
	ID           int64
	ProjectID    string
	CreatedAt    int64
	DataName     string
	FunctionName string
	Data         string
}

type ProjectMessageHistory struct {
	ID        int64
	ProjectID string
	CreatedAt int64
	Content   string
}
